server:
  port: 8082


security:
  oauth2:
    client:
      clientId: OrdixSampleID
      clientSecret: ordixSecret
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/user/me
      token-info-uri: http://localhost:8081/oauth/check_token